server {
    listen 8080;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    add_header Cache-Control "no-store, no-cache, must-revalidate";

    location = /health {
        access_log off;
        default_type application/json;
        alias /usr/share/nginx/html/version.json;
    }

    location = /env.js {
        add_header Content-Type application/javascript;
        add_header Cache-Control "no-store, no-cache, must-revalidate";
        expires -1;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
